### ISSUE TITLE
Calling updateLocale causes crash

### ISSUE THREAD

**Issue by MostafaAmerAts** [zeugma-solutions/locale-helper-android#50]
I'm calling updateLocale from locale aware child activity it shows black screen and it crash:

`E/ActivityInjector: get life cycle exception
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to android.app.servertransaction.ClientTransaction
        at android.app.ActivityInjector.checkAccessControl(ActivityInjector.java:24)
        at android.app.Activity.onResume(Activity.java:2011)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:310)
        at com.zeugmasolutions.localehelper.LocaleAwareCompatActivity.onResume(LocaleHelperActivities.kt:25)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1459)
        at android.app.Activity.performResume(Activity.java:8292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4625)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4667)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5640)
        at android.app.ActivityThread.access$3500(ActivityThread.java:261)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2182)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8163)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)`

**Comment by bakirLakaf** [comment]
same
any update!!?
